add header icon in sheet option using icon component.
gfx-geoprosp/gfx-spreadsheet pull request #6
Opened 2024-01-02 09:51 UTC by ardiantoosman4

2024-01-17 03:06 UTC, thejatmik commented
```
<Spreadsheet
  sheetOption={{
    scrollListener: {
      'first': () => {...},
      'last': (internal) => {
        ...req.GET...
         req.get(url).limit().offset()
         internal.addRow()
      },
    },
  }}
/>
```

2024-01-17 03:15 UTC, thejatmik requested changes

2024-01-17 03:15 UTC, thejatmik commented on src/App.tsx
> +        `http://localhost:3001/Users?_page=1&_limit=10`
example server for this request?
if possible i strongly suggest hosting dummy data as separated json or js object instead of url request

2024-01-17 03:15 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.types copy.ts
remove if unused

2024-01-17 03:15 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.tsx
> +    format = new Intl.DateTimeFormat(locale, dtf);
plz turn off your auto linter / auto prettier.
minimize changes to only lines you typed/write on your own, its hard to review the core functions if they're drowned between changes of singlequote to doublequote like this

would suggest to set ur linter to give warning/error instead of aggresively modify file on open/save.

2024-01-18 01:38 UTC, ardiantoosman4 commented on src/App.tsx
> +        `http://localhost:3001/Users?_page=1&_limit=10`
In the add-header-icon-comonent branch there is the db.json file needed to start JSON-server. To start the json-server sample run the command "npm run start-json-server". Json-server is needed to simulate the infinite scroll feature

2024-01-18 01:39 UTC, ardiantoosman4 commented on src/lib/components/Spreadsheet/Spreadsheet.types copy.ts
has been removed in the latest commit

2024-01-19 03:24 UTC, thejatmik requested changes

2024-01-19 03:24 UTC, thejatmik commented on src/HeaderIcon/Filter.tsx
> +import { ReactComponent as FilterIcon } from "./filter.svg";
add `import React` on tsx component

2024-01-19 03:24 UTC, thejatmik commented on src/HeaderIcon/Pencil.tsx
> +import { ReactComponent as PencilIcon } from "./pencil.svg";
add `import React` on tsx component

2024-01-19 03:52 UTC, thejatmik requested changes
changes required to pass rollup build script

2024-01-19 03:52 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.css
use more specific css selector
`div .rg-pane...` -> `.reactgrid-content .rg-pane...`
`div.unfocus ...` -> `.spreadsheet-style.unfocus ...`

2024-01-19 03:52 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.tsx
> +import "./Spreadsheet.css";
due to build script, place all css lines on `src/styles.css`
add just add new lines

2024-01-19 03:52 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.tsx
> +import "./Spreadsheet.css";
then remove line 50

2024-01-19 06:29 UTC, thejatmik commented on src/lib/components/Spreadsheet/Spreadsheet.css
remove file if unused

2024-01-19 06:41 UTC, ardiantoosman4 commented on src/lib/components/Spreadsheet/Spreadsheet.css
done-remove unused file

2024-01-19 08:55 UTC, merged

2024-01-19 09:01 UTC, thejatmik commented
published as `gfx-spreadsheet@0.1.4-rc.3`